language: node_js
node_js:
- '8'
script: yarn && yarn build
sudo: required
before_deploy:
- sudo apt-get install sshpass
deploy:
- provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_6d75a4dbbe4d_key -iv $encrypted_6d75a4dbbe4d_iv
  -in deploy.sh.enc -out deploy.sh -d
